--- #YAML:1.0
name:               Date-CommonFormats
version:            0.05
abstract:           Common date formats made simple.
author:
    - Chris Fulton <chris@masonqm.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Calc:           0
    Date::Format:         0
    Date::Parse:          0
    DateTime::Format::MySQL:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
